# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [11]:
print(np.__version__ )
print(np.__config__)


1.20.1
<module 'numpy.__config__' from '/Users/manish/opt/anaconda3/lib/python3.8/site-packages/numpy/__config__.py'>


#### 3. Create a null vector of size 10

In [12]:
# Null vector is with all element are zero
n=np.zeros(10)
print("Our null vector:\n",n)

Our null vector:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [19]:
arr=np.array([1,2,3,4,5],dtype="int")

print("Array is :\n",arr)

print("Number of element: ",arr.size)

print("Element size: ",array.itemsize)

mu=array.size*array.itemsize
print("Memory used: ",mu)


Array is :
 [1 2 3 4 5]
Number of element:  5
Element size:  8
Memory used:  40


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [20]:
np.add?


#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [22]:
a=np.zeros(10)
a[4]=1
print("a null vector of size 10 but the fifth value which is 1:\n",a)


a null vector of size 10 but the fifth value which is 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [26]:
q=np.arange(10,50,1)

print(q)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [31]:
array=np.array([1,2,3,4,5],dtype='int')

print("Orginal array:\n",array)

revarray=array[::-1]

print("reverse array:\n",revarray)

Orginal array:
 [1 2 3 4 5]
reverse array:
 [5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [40]:
# first create a 1 d array then we can modify to 3 X 3
d_1=np.arange(0,9)
print(d_1)

ans=d_1.reshape((3,3))

print("Ans is:\n",ans)


[0 1 2 3 4 5 6 7 8]
Ans is:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [43]:
arr=np.array([1,2,0,0,4,0])

print("Orginal array:\n",arr)

rejult=np.where(arr !=0)[0]

print("Index of non zero element:\n",rejult)

Orginal array:
 [1 2 0 0 4 0]
Index of non zero element:
 [0 1 4]


#### 11. Create a 3x3 identity matrix

In [32]:
# Indentical matrix
I=np.eye(3,dtype="int")
print("Indentical matrix:\n",I)

Indentical matrix:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values

In [37]:
Rarray=np.random.random((3,3,3))
print("Array is:\n",Rarray)

Array is:
 [[[0.25773026 0.1328659  0.42553486]
  [0.48301377 0.34396571 0.0748673 ]
  [0.85266463 0.18987659 0.65109236]]

 [[0.47400576 0.37727501 0.59386684]
  [0.98410725 0.62689721 0.28945411]
  [0.71681678 0.44568419 0.80702487]]

 [[0.40185929 0.22905132 0.26307021]
  [0.25759142 0.57787408 0.64979575]
  [0.53077488 0.26858037 0.8242103 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [36]:
Randarray=np.random.random((10,10))

print("Our array is:\n",Randarray)


print("Max:\n",np.max(Randarray))

print("Min:\n",np.min(Randarray))

Our array is:
 [[0.13639203 0.35798054 0.06272499 0.36065687 0.48041977 0.06400255
  0.3186058  0.6008941  0.24983597 0.99481187]
 [0.8836607  0.58688486 0.58063525 0.08495132 0.92839323 0.41164024
  0.58486564 0.24566652 0.82820687 0.35081163]
 [0.84264137 0.76960829 0.71759667 0.32360845 0.22380362 0.41356752
  0.50438743 0.62766693 0.08232523 0.32107733]
 [0.45600729 0.92999998 0.04194578 0.22363285 0.86673805 0.2265313
  0.95818256 0.01400219 0.25214766 0.44310775]
 [0.16710644 0.84434788 0.59394112 0.95000074 0.67903519 0.7705022
  0.22527294 0.82269357 0.77617026 0.4863186 ]
 [0.38076021 0.88517951 0.58478893 0.01790103 0.44072829 0.9495777
  0.9988222  0.90375302 0.12899778 0.32668192]
 [0.9308502  0.28841573 0.86924717 0.1366653  0.76018832 0.97355464
  0.44657159 0.64090729 0.5408735  0.10083103]
 [0.60676607 0.00214719 0.35641381 0.1908332  0.78084246 0.94746652
  0.51236657 0.21649429 0.92991007 0.22070043]
 [0.50261953 0.01551366 0.11007924 0.99222609 0.59314062 0.31957472


#### 14. Create a random vector of size 30 and find the mean value

In [42]:
# Our random vector
r=np.random.random(30)

print("Array is:\n",r)

m=np.mean(r)

print("Mean is = ",m)


Array is:
 [0.04818183 0.03400505 0.29223023 0.36991099 0.8660683  0.6352821
 0.09907511 0.62792345 0.35173546 0.61379142 0.6104623  0.31979509
 0.56261553 0.56964614 0.65999366 0.80634048 0.12334937 0.34796585
 0.71712633 0.32038367 0.94589038 0.92620728 0.75738758 0.17937295
 0.35607109 0.61401661 0.5356316  0.22152447 0.05104063 0.36736579]
Mean is =  0.4643463578011983


#### 15. Create a 2d array with 1 on the border and 0 inside

In [56]:
'''
1 1 1 1   1 1 1 1 1 0 0 1 1 0 0 1 1 1 1 1
1 0 0 1
1 0 0 1
1 1 1 1

'''
l=list(map(int,input("Input dimenstion:").split()))
n=l[0]
m=l[1]
arr=np.full((n,m),1,dtype="int")
arr[1:n-1,1:m-1]=0
print(arr)

Input dimenstion:5 6
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [66]:
#let array is

l=list(map(int,input("Input dimenstion:").split()))
n=l[0]
m=l[1]
a=np.zeros((n,m),dtype="int")
print("Your array is:\n",a)
a[0:n,0:1]=1
a[0:1,0:m]=1
a[0:n,m-1]=1
a[n-1,0:m]=1
print("Your array with border is:\n",a)




Input dimenstion:5 6
Your array is:
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Your array with border is:
 [[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [89]:
#nan
#false
#false
# nan
# true
#false



False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [73]:
arr = np.diag(1+np.arange(4),k=-1)
print (arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [77]:
arr=np.zeros((8,8),dtype="int")

arr[0::2,0::2]=1
arr[1::2,1::2]=1
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [81]:
a=np.random.random((6,7,8))

print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)
