# Numpy practise session

In [1]:
import numpy as np


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))# type of entity
print(arr.dtype)# datatype of numpy array element
print(arr.shape)# row & col how many
print(arr.size)# number of elements
print(arr.ndim)# dimenstion

# 1D array
a=np.array([1,2,3])
print(a.shape)
print(a.ndim)





#  Creating an numpy array

In [49]:
# from list
l=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="float")
print("Array from list:\n",l)

# from tuple
t=np.array((1,2,3))
print("Array from tuple:\n",t)

t2=np.array(((1,2,3),(4,5,6)),dtype="int")
print("Array from tuple:\n",t2)


# Creating n X m array with some specific property

# 3 x 4 array with all zeros
z=np.zeros((3,4),dtype="int")
print("Zero array is:\n",z)

#3 x 4 array with all  ones
p=np.ones((3,4),dtype="int")
print("Ones array is:\n",p)

# Indentical matrix(only square matric can be fromed)
I=np.eye(4,dtype="int")
print("Indentical matrix:\n",I)

# constant array
c=np.full((3,4),1,dtype="int")
print("Constant array:\n",c)

com=np.full((3,4),2+3j,dtype="complex")
print("Constant complex array:\n",com)

# creaating a random array

r1=np.random.random(5)
print("1 D random array with size= 5:\n",r1)

r2=np.random.random((2,4))
print("2 D random array :\n",r2)

# creating sequence of integers

# 1 D array with 0 to 30 with inc=5
q=np.arange(0,31,5)
print("1 D array with 0 to 30 with inc=5:\n",q)

#creating a sequence of 10 values in range 0 to 5
k=np.linspace(0,5,8,dtype="int")
print("creating a sequence of 10 values in range 0 to 5:\n",k)


# reshape array
arr=np.array([[1,2,3,4],[5,4,3,2],[1,2,9,8]])
newarr=arr.reshape(2,1,6)

print("Original:\n",arr)
print("Reshaped array:\n",newarr)

# flattern array
x=np.array([[1,2,3],[4,5,6]])
print("Original array:\n",x)

f=x.flatten()
print("Flattern array:\n",f)



Array from list:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Array from tuple:
 [1 2 3]
Array from tuple:
 [[1 2 3]
 [4 5 6]]
Zero array is:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Ones array is:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Indentical matrix:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Constant array:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Constant complex array:
 [[2.+3.j 2.+3.j 2.+3.j 2.+3.j]
 [2.+3.j 2.+3.j 2.+3.j 2.+3.j]
 [2.+3.j 2.+3.j 2.+3.j 2.+3.j]]
1 D random array with size= 5:
 [0.49249222 0.23457384 0.75575661 0.31295608 0.71457094]
2 D random array :
 [[0.53920024 0.1458204  0.77069821 0.40065295]
 [0.36009844 0.88812968 0.19861645 0.50394729]]
1 D array with 0 to 30 with inc=5:
 [ 0  5 10 15 20 25 30]
creating a sequence of 10 values in range 0 to 5:
 [0 0 1 2 2 3 4 5]
Original:
 [[1 2 3 4]
 [5 4 3 2]
 [1 2 9 8]]
Reshaped array:
 [[[1 2 3 4 5 4]]

 [[3 2 1 2 9 8]]]
Original array:
 [[1 2 3]
 [4 5 6]]
Flattern array:
 [1 2 3 4 5 6]


# Array indexing and Slicing

In [50]:
ar=np.array([[1,2,3,4],[4,5,6,7],[3,6,4,1],[4,3,2,1]],dtype="int")
print("Array:\n",ar)

Array:
 [[1 2 3 4]
 [4 5 6 7]
 [3 6 4 1]
 [4 3 2 1]]


In [53]:
'''
[
    [1 2 3 4]
    [4 5 6 7]
    [3 6 4 1]
    [4 3 2 1]
]

we want :
  5 6
  6 4
  
  ar=[row             ,   col          ]
  ar=[start:end+1:stpe,start:end+1:step]
'''
subarray=ar[1:3,1:3]
print("Subarray:\n",subarray)

sub2=ar[[0,1,2,3],[0,1,2,3]]
print("Subarray with dignal element:\n",sub2)

Subarray:
 [[5 6]
 [6 4]]
Subarray with dignal element:
 [1 5 4 1]


In [55]:
#Boolean array indexing

array=np.array([[1,2,3,4],[4,3,3,1],[3,5,7,1]])

cond=array>3

k=array[cond]

print("Boolean array:\n",k)

Boolean array:
 [4 4 5 7]


# Basic operation

- +=
- -=
- *=
- +
- -
- *
- x.dot(y)

In [69]:
ar=np.array([1,2,5,3])

print("Orginal:\n",ar)

print("Adding  1 to all element:\n",ar+1)

print("Subtract 1 to each element:\n",ar-1)

print("Multyply with 10:\n",ar*10)

print("Squaring each element:\n",ar**2)


ar+=2

print("Modifying array:\n",ar)

# Transpose of array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Orignal:\n",arr)
print("Transpose:\n",arr.T)

# some fxn
print("Orignal:\n",arr)
print("Max:\n",arr.max())
print("Min:\n",arr.min())

print("Row-wise max:\n",arr.max(axis=1))
print("Row-wise min:\n",arr.min(axis=1))

print("Column-wise max:\n",arr.max(axis=0))
print("Column-wise min:\n",arr.min(axis=0))

print("Sum of element:\n",arr.sum())

print("Cumsum:\n",arr.cumsum())
print("Cumsum along row:\n",arr.cumsum(axis=1))
print("Cumsum along column\n",arr.cumsum(axis=0))



Orginal:
 [1 2 5 3]
Adding  1 to all element:
 [2 3 6 4]
Subtract 1 to each element:
 [0 1 4 2]
Multyply with 10:
 [10 20 50 30]
Squaring each element:
 [ 1  4 25  9]
Modifying array:
 [3 4 7 5]
Orignal:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Orignal:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Max:
 9
Min:
 1
Row-wise max:
 [3 6 9]
Row-wise min:
 [1 4 7]
Column-wise max:
 [7 8 9]
Column-wise min:
 [1 2 3]
Sum of element:
 45
Cumsum:
 [ 1  3  6 10 15 21 28 36 45]
Cumsum along row:
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
Cumsum along column
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [70]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,3],[2,1]])

print("Array a :\n",a)
print("Array b :\n",b)
print("Addition of a & b :\n",a+b)
print("Subtraction of a & b :\n",a-b)
print("Multipliction of a & b(element wise) :\n",a*b)
print("Dot product of a & b :\n",a.dot(b))

Array a :
 [[1 2]
 [3 4]]
Array b :
 [[4 3]
 [2 1]]
Addition of a & b :
 [[5 5]
 [5 5]]
Subtraction of a & b :
 [[-3 -1]
 [ 1  3]]
Multipliction of a & b(element wise) :
 [[4 6]
 [6 4]]
Dot product of a & b :
 [[ 8  5]
 [20 13]]


# Universal fxn

In [75]:
a=np.array([0,np.pi/2,np.pi])
print("Sine value array:\n",a)
b=[1,2,3,4]
x=np.sin(b)
print("Sine value array:\n",x)

c=np.array([1,2,3,4])

print("Exponent array:\n",np.exp(c))

print("Squareroot:\n",np.sqrt(c))

Sine value array:
 [0.         1.57079633 3.14159265]
Sine value array:
 [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Exponent array:
 [ 2.71828183  7.3890561  20.08553692 54.59815003]
Squareroot:
 [1.         1.41421356 1.73205081 2.        ]


In [82]:
# Sorting

a=np.array([6,3,6,8,3,2,5])

print("Original:\n",a)

print("Sorted array:\n",np.sort(a))

b=np.array([[4,3,5,1],[4,8,3,9],[6,3,8,9]])

print("Original:\n",b)

print("Sorted:\n",np.sort(b))
print("Sorted:\n",np.sort(b,axis=None))
print("Row wise Sorted:\n",np.sort(b,axis=1))
print("Column wise Sorted:\n",np.sort(b,axis=0))

x=np.array([6,8,4,9,12,45,5,3])

print("Merge sort:\n",np.sort(x,kind="mergesort"))

Original:
 [6 3 6 8 3 2 5]
Sorted array:
 [2 3 3 5 6 6 8]
Original:
 [[4 3 5 1]
 [4 8 3 9]
 [6 3 8 9]]
Sorted:
 [[1 3 4 5]
 [3 4 8 9]
 [3 6 8 9]]
Sorted:
 [1 3 3 3 4 4 5 6 8 8 9 9]
Row wise Sorted:
 [[1 3 4 5]
 [3 4 8 9]
 [3 6 8 9]]
Column wise Sorted:
 [[4 3 3 1]
 [4 3 5 9]
 [6 8 8 9]]
Merge sort:
 [ 3  4  5  6  8  9 12 45]


# Stacking & spliting

- np.vstack(): along verical axis
- np.hstack(): along horizontal axis
- np.column_stack(): 1 d array as 2d array
- np.concatenate(): along specific array

In [89]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,3],[2,1]])

print("Array a:\n",a)

print("Array b:\n",b)

print("Vertical stacking:\n",np.vstack((a,b)))

print("Horizontal stacking:\n",np.hstack((a,b)))

c=[5,6]

print("Column stacking:\n",np.column_stack((a,c)))

print("Conctainate to 2nd axis:\n",np.concatenate((a,b),1))

Array a:
 [[1 2]
 [3 4]]
Array b:
 [[4 3]
 [2 1]]
Vertical stacking:
 [[1 2]
 [3 4]
 [4 3]
 [2 1]]
Horizontal stacking:
 [[1 2 4 3]
 [3 4 2 1]]
Column stacking:
 [[1 2 5]
 [3 4 6]]
Conctainate to 2nd axis:
 [[1 2 4 3]
 [3 4 2 1]]


# Spiliting
- np.hsplit
- np.vsplit
- np.array_split


In [90]:
a=np.array([[1,3,5,7,9,11],[2,4,6,8,12,14]])

print("Horizontal split axis into 2 parts :\n",np.hsplit(a,2))

print("vertical split axis into 2 parts :\n",np.vsplit(a,2))

Horizontal split axis into 2 parts :
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 12, 14]])]
vertical split axis into 2 parts :
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 12, 14]])]


# Some more Numpy Statstical fxn
- min,max
- mean
- median
- average
- variance
- Sd


In [98]:
a=np.array([1,2,3,4,5,6,7,8,9])

print("Array:\n",a)

print(np.mean(a))

print(np.median(a))

print(np.std(a))

Array:
 [1 2 3 4 5 6 7 8 9]
5.0
5.0
2.581988897471611


# Numpy random module
- rand: random value in given shape
- randn: rturn sample from standered normal distribution
- randint: return random int low to high
- random: retunn random float value open interval(0.0,1.0)
- CHOICE: GERATES A random sample from 1 d array
- shuffle: shuffle the content of sequence



In [135]:
from numpy import random

a=random.rand()
print(a)

b=random.randn()
print(b)

c=random.randint(0,5)
print(c)

arr=[1,2,3,4,5,6]

choice=random.choice(arr)
print(choice)


f=[1,2,3,3,4,5]
random.shuffle(f)
print(f)

f=[1,2,3,3,4,5]
random.permutation(f)
print(f)

0.6951275374008146
2.194509808277586
3
1
[2, 4, 1, 5, 3, 3]
[1, 2, 3, 3, 4, 5]
